apiVersion: sonarqube.sonarqube.io/v1alpha1
kind: SonarQubeGroup
metadata:
  name: developers
  namespace: sonarqube
spec:
  instanceRef:
    name: sonarqube
  name: developers
  description: Engineering team — read/write on most projects
